### ISSUE TITLE
https://twitchtv.tv no is dead !

### ISSUE THREAD

**Issue by marc-farre** [GreenMeteor/humhub-twitchtv-module#3]
https://twitchtv.tv doesn't work anymore...

**Comment by Felli** [comment]
You use `https://www.twitch.tv/embeded/USERNAME/chat` now, I'll be updating this in a few seconds.

**Comment by Felli** [comment]
FIxed in v1.0.7!

**Comment by marc-farre** [comment]
GREAT ! Thanks very much for your reactivity !
